Feature/fp2
greenfrontend/study pull request #3
Opened 2021-04-12 16:54 UTC by greenfrontend

2021-04-12 17:03 UTC, Andrew8xx8 requested changes

2021-04-12 17:03 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for item in self
`each` нужно реальзовать используя рекурсию

2021-04-12 17:03 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_map
`map` нужно реализовать через `reduce`

2021-04-12 17:03 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +      def my_compact
`compact` нужно реализовать через `reduce`

2021-04-13 04:04 UTC, greenfrontend commented on test/exercise/fp2/solution.rb
> +        for item in self
переписал

2021-04-13 04:05 UTC, greenfrontend commented on test/exercise/fp2/solution.rb
> +      def my_map
переписал

2021-04-13 04:05 UTC, greenfrontend commented on test/exercise/fp2/solution.rb
> +      def my_compact
переписал

2021-04-14 10:04 UTC, Andrew8xx8 approved these changes

2021-04-14 10:47 UTC, merged